---
default_language_version:
  python: python3.10
default_stages: [ commit ]
fail_fast: false
minimum_pre_commit_version: 2.20.0
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: mixed-line-ending
        args: [ "--fix=lf" ]
      - id: check-yaml
      - id: check-added-large-files
        exclude: ^notebooks/.*$
      - id: check-toml
      - id: check-yaml
  - repo: https://github.com/pycqa/flake8
    rev: 3.9.2
    hooks:
      - id: flake8
        additional_dependencies: [
            'flake8-comprehensions==3.10.0',
            'flake8-debugger==4.1.2',
            'flake8-bugbear==22.10.27',
            'flake8-no-pep420==2.3.0',
            'flake8-eradicate==1.4.0',
            'flake8-docstrings==1.6.0'
        ]
        args: ["--docstring-convention=numpy"]
  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        name: isort (python)
  - repo: https://github.com/ambv/black
    rev: 22.10.0
    hooks:
      - id: black
  - repo: https://github.com/asottile/pyupgrade
    rev: v3.2.2
    hooks:
      - id: pyupgrade
        args: [--py310-plus]
        exclude: ^experiments/.*$
  - repo: https://github.com/jorisroovers/gitlint
    rev:  v0.17.0
    hooks:
      - id: gitlint
  - repo: https://github.com/pycqa/pydocstyle
    rev: 4.0.0
    hooks:
      - id: pydocstyle
