stages:
  process_daquar:
    cmd: python pipelines/process_daquar.py
    deps:
    - data/raw/daquar/data_eval.csv
    - data/raw/daquar/data_train.csv
    - pipelines/process_daquar.py
    outs:
    - data/processed/daquar/daquar_train_flattened.csv
    - data/processed/daquar/daquar_eval_flattened.csv
  generate_vqa_v2_sample_answers_space:
    cmd: PYTHONPATH=. python pipelines/process_vqa_v2_sample.py
    deps:
    - pipelines/process_vqa_v2_sample.py
    outs:
    - data/processed/vqa_v2/vqa_v2_sample_answers_space.json
