stages:
  process_daquar:
    cmd: PYTHONPATH=. python pipelines/process_daquar.py
    deps:
    - data/raw/daquar/data_eval.csv
    - data/raw/daquar/data_train.csv
    - pipelines/process_daquar.py
    outs:
    - data/processed/daquar/daquar_train_flattened.csv
    - data/processed/daquar/daquar_eval_flattened.csv
  generate_vqa_v2_sample_answers_space:
    cmd: PYTHONPATH=. python pipelines/process_vqa_v2_sample.py
    deps:
    - pipelines/process_vqa_v2_sample.py
    params:
      - vqa_v2_sample.answers_space.include_alternative_answers
    outs:
    - data/processed/vqa_v2/vqa_v2_sample_answers_space.json
  generate_vqa_v2_raw_answers_space:
    cmd: PYTHONPATH=. python pipelines/generate_vqa_v2_raw_answers_space.py
    deps:
    - pipelines/generate_vqa_v2_raw_answers_space.py
    - data/raw/vqa_v2/examples/vqa_v2_answers_space_raw_example.json
    params:
      - vqa_v2.answers_space.raw.copy_example
      - vqa_v2.answers_space.raw.include_alternative_answers
    outs:
    - data/raw/vqa_v2/vqa_v2_answers_space_raw.json
  process_vqa_v2:
    cmd: PYTHONPATH=. python pipelines/process_vqa_v2.py
    deps:
    - data/raw/vqa_v2/vqa_v2_answers_space_raw.json
    - pipelines/process_vqa_v2.py
    outs:
    - data/processed/vqa_v2/vqa_v2_answers_space.json
